# Generated by Django 3.2.7 on 2021-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='played_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budget',
            name='time_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
