# Generated by Django 3.2.7 on 2021-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='model',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Role-Playing', 'Role-Playing'), ('Strategy', 'Strategy'), ('Adventure', 'Adventure'), ('Causal', 'Causal'), ('Simulation', 'Simulation'), ('Sports', 'Sports')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='theme',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Open World', 'Open World'), ('Sci-Fi', 'Sci-Fi'), ('Space', 'Space'), ('Survival', 'Survival')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Steam', 'Steam'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo')], max_length=50),
        ),
    ]
