# Generated by Django 3.2.8 on 2021-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0006_auto_20211029_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Role-Playing', 'Role-Playing'), ('Strategy', 'Strategy'), ('Adventure', 'Adventure'), ('Causal', 'Causal'), ('Simulation', 'Simulation'), ('Sports', 'Sports')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Steam', 'Steam'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Open World', 'Open World'), ('Sci-Fi', 'Sci-Fi'), ('Space', 'Space'), ('Survival', 'Survival')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Asia', 'Asia'), ('North America', 'North America'), ('Europe', 'Europe'), ('Africa', 'Africa')], max_length=1000),
        ),
    ]
